replicaCount: 1

image:
  repository: wbrymo/react-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false  # Disable ingress since LoadBalancer is handling traffic
