replicaCount: 1

image:
  repository: wbrymo/java-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP  # Ingress will expose it; no need for LoadBalancer
  port: 80

resources: {}

ingress:
  enabled: true
  host: backend.local  # Temporary/dev-only placeholder. Replace if needed.
  path: /
  pathType: Prefix
