replicaCount: 1

image:
  repository: wbrymo/java-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: java-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
